### ISSUE TITLE
Support higher time precision

### ISSUE THREAD

**Issue by jalaziz** [timonwong/cyksuid#22]
The original blog post introducing `ksuid` suggested that a higher time precision could be offered by sacrificing payload bytes.

It would be great if this library could support millisecond precision as an alternative.

Looking at alternatives, it seems 48-bits are generally sufficient for storing the timestamp. The alternative [svix-ksuid](https://github.com/svix/python-ksuid) seems to use 5 bytes presumably due to the modified epoch but as result only offers 4ms precision.

**Comment by jalaziz** [comment]
I would be happy to try and contribute this, but looks like the python3-only PR changes implementation details so will have to wait for that. Also, I'd be curious if you have a preference on the overall approach (parameterizing the current API or introducing new classes and functions)?

**Comment by jalaziz** [comment]
Amazing!

To be honest, the `svix` API isn't amazing, but I understand why you might want to be compatible with it.

That being said, are you considering 40-bit timestamps for compatibility or would you also offer 48-bit timestamps?

**Comment by timonwong** [comment]
> That being said, are you considering 40-bit timestamps for compatibility or would you also offer 48-bit timestamps?

All of them, 32, 40 and 48

See #24, it's still working in progress since I have a big refactor

**Comment by timonwong** [comment]
@jalaziz I dont find any reference doc / implementation about 48bit timestamp, do you have one?

**Comment by jalaziz** [comment]
@timonwong Not with `ksuid`. However, the `ulid` spec uses 48-bits and it's fundamentally the same except that `ksuid` supports more random bytes:
* https://github.com/ulid/spec
* https://github.com/ahawker/ulid/blob/master/ulid/providers/default.py#L13
* https://github.com/mdomke/python-ulid/blob/master/ulid/__init__.py#L84-L99

If I'm not mistaken, with `ksuid` and 48-bits, you actually extend the lifetime since you only need 42-bits to fully represent the timestamp down to 1ms. However, since we want to align to byte boundaries for sorting, you have to jump to 48-bits, which means the timestamp now has more bits available to it (the timestamp portion can representing larger numbers) at the expense of extra randomness.
